<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAotCompatible>true</IsAotCompatible>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/jetelain/PmadGit</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>Low-level Git wire protocol and packfile utilities for .NET.</Description>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>Julien Etelain</Authors>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pmad.Git.LocalRepositories\Pmad.Git.LocalRepositories.csproj" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.102" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Pmad.Git.HttpServer" />
		<InternalsVisibleTo Include="Pmad.Git.RemoteClient" />
		<InternalsVisibleTo Include="Pmad.Git.Protocol.Test" />
		<InternalsVisibleTo Include="Pmad.Git.HttpServer.Test" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>

